DELETE   http://localhost:3001/api/persons/3

###
POST   http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "banani Harbani",
  "number": "054542354"
}

###

GET   http://localhost:3001/api/info